version: '3'

services:
  ## Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=transactions --if-not-exists --bootstrap-server=kafka:9092 --replication-factor=1 --partitions=1 && 
        kafka-topics --create --topic=transactions_result --if-not-exists --bootstrap-server=kafka:9092 --replication-factor=1 --partitions=1"
        
  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021

  ## Payment Gateway
  gateway:
    build: ./fc-payment-gateway
    entrypoint: wait-for gatewaydb:3306 -t 40 -- go run cmd/main.go
    volumes:
      - ./fc-payment-gateway:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9094
      - MYSQL_HOST=gatewaydb
      - MYSQL_DATABASE=gateway
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    depends_on:
      - gatewaydb
      - kafka

  gatewaydb:
    build: ./fc-payment-gateway/.docker/mysql
    tty: true
    volumes:
      - ./fc-payment-gateway/.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gateway
      - MYSQL_ROOT_PASSWORD=root

  ## Backend
  backend:
    build: ./fc-backend
    entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - ./fc-backend:/home/node/app
    depends_on:
      - db
      - kafka
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  db:
    build: ./fc-backend/.docker/mysql
    tty: true
    volumes:
      - ./fc-backend/.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fc
      - MYSQL_ROOT_PASSWORD=root
  
  # Frontend
  frontend:
    build: ./fc-frontend
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - ./fc-frontend:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - backend