apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway/deployment.yaml
  - gateway/secret.yaml
  - backend/deployment.yaml
  - backend/secret.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
